apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello.name" . }}
  labels:
    {{ include "hello.labels" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "hello.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "hello.name" . }}
      spec:
        containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullpolicy }}
            ports:
              - containerPort: 8080
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              fsGroup: 2000
              allowPrivilegeEscalation: false
