apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello.name" . }}
  labels:
    {{ include "hello.labels" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ include "hello.name" . }}
