apiVersion: v1
kind: service
metadata:
  name: {{ "include "hello.fullname" . }}
  labels:
    {{ include "hello.labels" }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.type }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ include "hello.name" . }}
