image:
  repository: server_hello
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: NodePort
  port: 8080      
  nodePort: 30001  

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "200m"

